// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWGFI3RIGfdAeGl_c6yuHDyiuVwSdixjk',
    appId: '1:484688005107:web:f8d1cfea91f6d6f15fb486',
    messagingSenderId: '484688005107',
    projectId: 'chatboard-app',
    authDomain: 'chatboard-app.firebaseapp.com',
    storageBucket: 'chatboard-app.firebasestorage.app',
    measurementId: 'G-DS5EJMY925',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWX3DRqQcdCw-BeXe10cRVtlJE3H2nu4o',
    appId: '1:484688005107:android:adc57701e84cc9fa5fb486',
    messagingSenderId: '484688005107',
    projectId: 'chatboard-app',
    storageBucket: 'chatboard-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWh2-VB1hVQfsvxluJUl3vuENjIoBxHYE',
    appId: '1:484688005107:ios:c798f2023e64e6a25fb486',
    messagingSenderId: '484688005107',
    projectId: 'chatboard-app',
    storageBucket: 'chatboard-app.firebasestorage.app',
    iosBundleId: 'com.example.chatboards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWh2-VB1hVQfsvxluJUl3vuENjIoBxHYE',
    appId: '1:484688005107:ios:c798f2023e64e6a25fb486',
    messagingSenderId: '484688005107',
    projectId: 'chatboard-app',
    storageBucket: 'chatboard-app.firebasestorage.app',
    iosBundleId: 'com.example.chatboards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWGFI3RIGfdAeGl_c6yuHDyiuVwSdixjk',
    appId: '1:484688005107:web:d392c7952ee0c80b5fb486',
    messagingSenderId: '484688005107',
    projectId: 'chatboard-app',
    authDomain: 'chatboard-app.firebaseapp.com',
    storageBucket: 'chatboard-app.firebasestorage.app',
    measurementId: 'G-MJ30LK99YK',
  );
}
